language: scala
scala: 2.12.8
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "dU6WnXUr+Ygndc3Xipf8Pkff83EwSKwU1bSUB6t/H0dZqnwADK6+QekiaJx1QCKeiee9mnXHuyGhI5L35QUcifps1lR7a9KAONFLCJ34bohd7tjMA1SCN/0DdQ7ufXiQCwKKNqovKAWCZ3QhrCL7MibXgm6WnCbWNcQmz1/31v/Xu1o4WiCeEj+LuPI8/jfdUhV98nI2b6fFje5rzedPv2UqHUKu/wt+tyiwBQDY4OOB8UP04j28i9GXhDllXOeKNtHY2b1+6Yptfs64RM+CE/elmSvRhzzb/ck/Wbwzg3DFJJ54tAQyRf+PFcgwaW9zMF5RvNgyCLbiNzyXG4SRARrTEZyHpm+pa/wZWtnyua8ofmYAkZplxU06abot1wgV93f4PVNsU5d5+67B+0PWavIlp9QRqprQEQjDkCWUNuRXiwRLHQhptrv7RrU/6sBEdfjyPPJ/5UFiPSJ08L0H6MYDbcznqeSFWR/IuJbvAvK7L6/DXskV5VYl3W9XnyzozsABrKxTpwBhz/Vot3vcHwBNd4cMO4pRbnDOlOtaTl70GC7mDmxMJqx9NssLu1yGPnRZRvR2dvgW2tgAgm85yXppH49ArZEAlADLdEQyz64W4J3sc/LPxC0QBtdpXdOCXpWH6E8W8HUEKt7Djrb1xzgMzk+xlSypaIiLUyEuVc8="
    # GITHUB_TOKEN
    - secure: "TegVkQR7wNba3icySmk2nrfkzRXIujZO4qT4jpQLcCAU/sKVR+UEUUH62l6/Pu6Ju1m821/o8raAwPRmh0hFD6LLsBtcupiAsF/b0qSbL07B/CZt4uzzlFQzGJB0UI4O/+4cR/5mEhXR3lBwy7uBpUYC8IzBr/ToSalO3i6N9EI9Dl9UEAi1t2Xh9j+1hreDQcpRS2qX5/s+WVFNTzWyqeB7w5CzHJjRwwcy8Yf+kQeu3P/Vs51wV5bRQrjkLRHHsD5dVhIrKyAMLdn7XhBwiaILgybY/wFEuufmYjZiuoK63itQ7eqefy19hAhy4IOpCyaxVmKzaSClDRxg0h2OhR/84THno5qhJ73cGkmnT+lev0Kyk5WYxTL5JyZ87dPWCeO+HGXBO2i54lgufxVauy8Qwb/AytDAgl+FEBbrbjmR5p0etsipHlGZZIN+W1ZRqnwql8kxzKcqc2JOS7Zay3mLkGGE+ivHQBBEGrcEF/7GX/14lt9fAFxZKsuIkJfPjh5pMS8ZR8OEQOiRT/Xz1jw5ysBEQLUoRPsznDS6s3Pe8zJe4baFulS9QO1KtPl1jvG3J0/XrG7tlkZtmg7AY8sxBibw59hWZBBFMPhyRn2TJMlv79bDcqCGypLa96JP4Ic5/1ml1DpqMQB92p5jyzn38kbf0MbojhLrxVoREqE="
    # GITHUB_ACCESS_TOKEN
    - secure: "mhGyfooIvtzJAUf2P+Z6QpwV7/mrefKWxJB0YNf1Ws7waJpS+0yOzYXclK9O1cqQojF3ZqYeYJv052XTgPeHbstP7yZeNf8JAKV7aaZBUf5VotWc45E+R1/klSoH5ipCjVnYCcLYRRvopi5GNcvhp3Mdl/r8kBUPLgbmCtORm9XWznlYJ3ti4NkZ8HYL9POa+utbP5bueWnsm4unX2AJgZQSvhI7C+V8zZm80gu2wRhDK5TSfvlBCiJsvt5Wiw3Q9DF2u8mxU7SmtYsaMp5h8W5s74XRDmL7/RixjtsKpAe+LphQemd6YEXGnOvk0li1zK9g3pUOs1ezhfNuYqsZo6ddnRQ6JiXzBia3Y1e9WrY7QO8uEq3PkurcdoSzaaU5ojB11OAI3TEp2RoVHWJzOft27o3QxFvT4NH2incflGp1ExRjvEuij9uK2QmJnFmExmkEwJMa7Cx5VjUXF89qu4liZ14f4VL1JIb87f9upiwALypw9LOesj9TIioQq1rmHkXMYATRssPipklTExu4gs6PYNfIZXsjhmvwTB6a+n/saOeHnq2ecqjiQy1XOx5B6rxsopj3Q05FbF+Co0/+uO1Ts1AcgyalwHZ+6Sq8StKsoi0S/hdVoQeJ8nf8ezDJUjIHWXhYz6deQG29UdGswySMfJCAayy0x2xIUQJZmBk="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "oGZX+9QTHdbpaLp54dKX6hPpxC7Bfwr/kgTZaMdyyLyOVsGpr+muMJxZOa9bILdMCs/o0oDBBXFrt+TOExvG2sLxu0kBvg8ekV5aDAAZ8nud71NYtl0E1O9D86+x05NuxLmfGNaxNtwgTdE2crCEfhfRJ3LmygdRhZz7xxtgLuOyjLxt4gKSq8V+KKt5erkSUpCi0DYbaFroaBvB1kLZ2kr6H7LANkb337UFZ/4haZVcSDrITd42Vb8h0OWeRsviKe/9tuwSL0Xc/ORKyn4usPiVpTK4owEQlfw5ZDsdZL+QSb985/ej3Iv/J+38YEIiR1qtkB+6K8wLCrm6pFUlvFgIg2ZPdFVoRz4+pT0isblSJggJoHs2LpJh7UPbCeOEEMd/z8B59Ar+2hHCCa9bSLaG9unDa/3fzNQjp8m8pM7vTIqDyeEJLjgu6j+Mbze4JHiQL3fF4gHD8weG1qeb8T2QGaJlk3NtilnsepsHiT5dSrp0FCt7rM311EI8X4hkoK2/zFnniOSkQ8Jl40H1crGtcmrHydWx1Vqh6B8oqNY5UBR9ZBe8kPMm5uUi2biaNlDmIHB25+GD1jZCnfvG+4SVQoEN0oSxUauP6Wu12KBgnFPTZbhf8+tEMXM3YdQ7shNsSt0D0gxkY+0Uldgy/JZumbJVH+ur6a8fPh2wKR8="

install:
  - mkdir scripts
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
    - set -e

    - $SBT ++$TRAVIS_SCALA_VERSION test

    - |-
      if [ $TRAVIS_PULL_REQUEST == "false" ] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        $SBT transferPublishAndTagResources;
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/async-blobstore';
      fi

after_success:
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
