language: scala
scala: 2.12.8
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "IexNDX5MrScoWRhIvd+lAsGmtKAsyKd2otO7xZi5WQJXUDRv5ZUjE+/erJx0A5pS/vNfxuHTRpZ8L7sXC7fuiOk5aItbjAUdkYuDXyJ7/yc4Ybb+kGv+DU3n/KB6ofpPigGSU9DfccjsfJRw5CXtSsvHVBR3Cobf6iuFDAS6pw96iITjOA4pHd6/c2W+boW4hsVEzN+wH0RDYO2PTRurjWTYy0gQDYnch4xQddjpqxVjAED4yRfjjopt5Q8+LczgKj+OM55ghxuigwXclPI8o+q4ju3rB5fVZVkxJIqFLpWpIJIAPu/p6XMcMdExj3p3R5Cp/qP3jnRjfyTjWmSm1Gu+jP9pO1l5E555ANQCl/nqIAs47Jsy8Qi+SIJwnDbCbiN4JOMbiWYoVoJOM7f6qwd7WlVrmBkMN9YpdX8tRviwmesbP8PTtg45ZiiSqOeqWg8r5CpkHEP9dqJ9CjIHKBUe00va22/M3Kj4vZdPdzqWLuQt2bTizuKaDJbd5rZot7Sd/Br+Gh2OX/ddJyjILlWCiyGbcPm6Zf45R4oLEMlkc9vXuZvgqdO9BpOOa/BYXVaAa/KhrHGu/OVFxMxtCCjLBrFUxqI88yhck8xUEeKVydbKg+BZrff7ns9Al9FUSil9qjwKh89lMnABH4K+WczugbXw61+ooZ2WIgeofxI="
    # GITHUB_TOKEN
    - secure: "t2qmGtx/63aP8SAy3vqxwYAHMlhm//BOJkLmj33mCUxNCtmbbccItaj/40h78I65eYwqToyUzKE03N+YE4FaYX7fG+lvX6uh74b9AgjJimXLbnMBAq1RpiZjG8TIR3Sssi2hS56egY5Tecg1aoEjwM7kRZ2HGHlwZe1WBvHshf8uiVEgKNnJLYiLyDb0/z+gjQ9vKFs4bOgjkVAF/OIBs4si/9EpkOd6zMoaSp0J2XenWV/VIuTjelvxG5nrpHO9t0d6srQqJa+R1q5z/J1s+TIXjfYku6OzptRzNtKLudqXsLCvjYPwzER+0gOAUxHK77RvrKKhkrdg9ZnHKam1zte/6oiK1nfXUzENQw7MsFX0DDHOySdKe22TLok8bd1UHFR7LIvOUEuk6Et22Zq202/mDdwtGZPaWo2lFgPEeku+TBdcrEawOyw7BfBVpflwamtdfcSTSk/JJBaE4VchuZFWxhbSUW3LPBdzSI+Itn8SeM3O2MGED67mPI2cEuRTU7z8l7G6rqtmTtL/x81+oe68GFvdVBfzrxEidszM1RmZN7CBrCCYPwEvvogQoChe/cp63I4L9SJaesgXNRdYXvYv11NanrTGg/3210dixDwKa6fES6lNL+JB9IIi687T7g99LKBqC9HJm0eOOVCAC5A6JJ3y/U5rL4Hu4QiRP2c="
    # GITHUB_ACCESS_TOKEN
    - secure: "V4ee1IOQ2cTXZz2GnpSH1NUQluSeKsLGfYbhOySpZXznl9VKUDDxU1gPMCq8HdJOMzWHch7zIpRa5jfZfzEjSWc9Bg1tORttHt1xLvCbSgJfBfAgILqMMPaKReilvMwIx6j+xIm5V1FevDE0+1SRjT4dAQONymdzKdEZmt2ggPBlOlv/VTx5QvYwJJEwTc7L5ZxH+/855BGt7J8pIjMw2+GrQMvzSW+tSPLp365IveFobafNm/K/X3spGPJvrbYEM2BiHlEIMaox/v166apLbYjoRVOen/rm9wtQe3A5tsJmLU3elyIW78K3o0cEsPBVhHJqEiVHLUoYHQyCQOyj3U6ARdHXTTGeplkvAFOLb/ZLZPdfOhg3fkDxq0IhUDM3QPbExH3kAr9oosKszwyuQ3VICAF3SKFKKjjUDi1SCrn2nR7ykbPIVPZmX99MARso6EHmPlX8ej1XJSc4rW7ySIxB5iI9YiGb//XUUD4VbOcvlxUNQ+02oTfocVV42SOq40Jkjte5XbH7mlTJ44te0ie9xbWUozJOthwlOKoRhnD79lRUpXwZdP4mFz/E33tZQIT8AvMyr/x2+Eg5rVG7y5idGvwBCfigm6iaxdJfgQ4xonYrZAxRrqM0llKMrAVd+xUoAdIPBHuNphcuuFd3hIoPSXM5jQa7LfRC7KBfAR0="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "HwTt3onzqm4RK+yBQpnydBlUR9MQHuPTX46S00WWzl5k0zCuYATZ71txIbwMEk9+FujwbzaVsFzROjZWknk5PJLP5Sq1V0/PH+vFS4n8hJyj2ZeOMH8sQQhJw9p1DIroqzLZ2YfOaWloggSnX2NPQPGNRUYqBcSxRfYTqpbITGNrQt/bMUqAJjBdrEiO5SM/wCLPUv8ir7+b4p0xqoTeziPISkBWh6ma0EI8h4evs/DSxJD7CizmBGMMNO4Ivodz7aTQVIvOnAzLoraboR5XTCuRC81K+8enaPU79rqqn+mWX9pZa+DHJPuA2WOigIO9T8sBQIuMd0346SeAPmO5zKIXn1MUEA20CbO51kFk6zQ2XAobJzHU5Dz08tZDEAaI9AOagCBEN6yRjKrD76RQQsQIfEOBjSv4zKj9W0wmqifvXKbilUubJRxVUSqAKmHMFqAwvI1WOY0YkA6ziUIB+CXsKSbs/QyIoXiC5k4eI/8zaq5zOcxNBE+9rZVOAB45rDsQtB6+YYwAGtTSzJfgGGjruAwam30Vw1wdaDNJQuEafXxTx6Q83bUqM1B5hQ0bpckkkciAU+sE3dY8Ozi5Kq+DwaNHRA2OJW5/ozWSmxcGAhUgeFUxh1Gy4CRwbkSzwS3GWstdV9kUzMvxVguMwSBFV2xTJ68TSJohVl3cxSE="

install:
  - mkdir scripts
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
    - set -e

    - $SBT ++$TRAVIS_SCALA_VERSION test

    - |-
      if [ $TRAVIS_PULL_REQUEST == "false" ] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        $SBT transferPublishAndTagResources;
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/async-blobstore';
      fi

after_success:
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
